/////// Meet Actions
export const CREATE_MEET = "CREATE_MEET"
export const UPDATE_MEET = "UPDATE_MEET"

export const GET_MEET_SUCCESS = "GET_MEET_SUCCESS"
export const CREATE_MEET_SUCCESS = "CREATE_MEET_SUCCESS"
export const UPDATE_MEET_SUCCESS = "UPDATE_MEET_SUCCESS"
export const REMOVE_MEET_SUCCESS = "REMOVE_MEET_SUCCESS"


///// Switch Theme
export const SWITCH_THEME_SUCCESS = "SWITCH_THEME_SUCCESS"
